[server]
headless = true
runOnSave = true

[theme]
base = "light"
primaryColor = "#0A84FF"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"


